export const paths = {
  home: "/",
  login: "/login",
  cadastro: "/cadastro",
  lembrarSenha: "/lembrar-senha",
  buscaUf: (sigla: string) => `/busca/uf/${sigla}`,
  buscaTag: (slug: string) => `/busca/tag/${slug}`,
  noticia: (id: string) => `/noticia/${id}`,
  leitorPerfil: "/leitor/perfil",
  leitorComentar: (noticiaId: string) => `/leitor/comentar/${noticiaId}`,
  autorPerfil: "/autor/perfil",
  autorComentar: (noticiaId: string) => `/autor/comentar/${noticiaId}`,
  autorNoticias: "/autor/noticias",
  autorNoticiaNova: "/autor/noticias/nova",
  autorNoticiaEditar: (id: string) => `/autor/noticias/${id}/editar`,
  editorPainel: "/editor/painel",
  editorPerfil: "/editor/perfil",
  editorPublicar: (id: string) => `/editor/publicar/${id}`,
  editorNoticiaEditar: (id: string) => `/editor/noticias/${id}/editar`,
  adminDashboard: "/admin/dashboard",
  adminUfs: "/admin/ufs",
  adminUfNova: "/admin/ufs/nova",
  adminUfEditar: (id: string) => `/admin/ufs/${id}/editar`,
  adminCidades: "/admin/cidades",
  adminCidadeNova: "/admin/cidades/nova",
  adminCidadeEditar: (id: string) => `/admin/cidades/${id}/editar`,
  adminTags: "/admin/tags",
  adminTagNova: "/admin/tags/nova",
  adminTagEditar: (id: string) => `/admin/tags/${id}/editar`,
  adminPerfis: "/admin/perfis",
  adminNoticias: "/admin/noticias",
  adminNoticiaEditar: (id: string) => `/admin/noticias/${id}/editar`,
  adminUsuarios: "/admin/usuarios",
  adminUsuarioEditar: (id: string) => `/admin/usuarios/${id}/editar`,
  adminComentarios: "/admin/comentarios",
} as const;
